### PR TITLE
[Fix] 14 Add Catalog Metadata Returns No Error

### PR DESCRIPTION
**Pull request by Conundraah**
- changed return type of SetMetadataAsync from Task to Task<ActionResult<object>>

### CODE REVIEW

**Comment by Conundraah** [comment]
Interestingly the method appears to not ProtectCatalogAsync even enter the lambda-function when SetMetadataAsync's return type is Task.

**Comment by Apollo3zehn** [comment]
I think the following code block has multiple issues (lines 494 - 505):

```cs
var response = ProtectCatalogAsync<object>(catalogId, ensureReadable: true, ensureWritable: false, async catalogContainer =>
{
    var canEdit = AuthUtilities.IsCatalogWritable(catalogId, catalogContainer.Metadata, User);

    if (!canEdit)
        return StatusCode(StatusCodes.Status403Forbidden, $"The current user is not permitted to modify the catalog {catalogId}.");

    await catalogContainer.UpdateMetadataAsync(metadata);

    return new object();

}, cancellationToken);
```

1. `ensureReadable` should be `false`
2. `ensureWritable` should be `true`
3. The subsequent lines containing `canEdit` can be removed because `ensureWritable` is now `true`

I think I caused this mess when I introduced the `ensureReadable` and `ensureWritable` without properly updating this method

**Comment by Apollo3zehn** [comment]
The rest looks fine :-)

**Comment by Apollo3zehn** [comment]
I fixed the mentioned issues above (because they are unrelated to this issue) and rebased your changes to new newest commit. I am now running on the new .NET 9 release (its much faster now to compile again :-)) and I cannot reproduce the original issue. So if you cannot reproduce it as well, we might just close this P/R.

**Comment by Apollo3zehn** [comment]
Sorry for the chaos, I changed the method implementation to ensure the catalog ID is correct. During that change I had the need to change the return type to `Task<ActionResult<object>>` which is exactly what you tried to to in this P/R. Because now changes were left now, GitHub automatically closed the P/R.

**Pull request closed without merging**
